services:

  app:
    build:
      context: .
    container_name: parking-system
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/parking_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: parkingpassword
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: parking-mysql
    environment:
      MYSQL_DATABASE: parking_system
      MYSQL_ROOT_PASSWORD: parkingpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-pparkingpassword"
        ]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql-data: